export { snipByCSS } from './methods/snipByCSS'
export { snipByJS } from './methods/snipByJS'
export { unsnip } from './methods/unsnip'
export { getLines } from './utils/getLines'
export { supportsCSSMethod } from './utils/supportsCSSMethod'
